export interface Cursos {
    data: Data;
}

export interface Data {
    cursos_estudiante: CursosEstudiante[];
    cursos_docente:    any[];
}

export interface CursosEstudiante {
    id:                     number;
    course_id:              number;
    persons_student_id:     number;
    id_carga_curso_docente: string;
    codigo:                 string;
    ciclo:                  string;
    estado_matricula:       string;
    estado:                 string;
    created_at:             null;
    updated_at:             null;
    deleted_at:             null;
    semester_id:            number;
    origen_matricula:       string;
}

// Generated by https://quicktype.io

export interface Unidades {
    data: Data;
}

export interface Data {
    id:                     number;
    nombre:                 string;
    id_carga_curso_docente: string;
    estado:                 string;
    programa_estudio_id:    number;
    persons_teacher_id:     number;
    id_carga_curso:         string;
    descripcion:            null;
    portada:                null;
    portada_miniatura:      null;
    grupo:                  string;
    ciclo:                  string;
    aula:                   null;
    idioma:                 string;
    consultas:              string;
    inscripcion:            string;
    chat:                   string;
    programa_estudio:       ProgramaEstudio;
    persons_teacher:        PersonsTeacher;
    units:                  Unit[];
}

export interface PersonsTeacher {
    person_id:           number;
    programa_estudio_id: number;
    cargo:               null;
    orci:                null;
    sede_area_id:        number;
    estado:              string;
    created_at:          Date;
    updated_at:          Date;
    deleted_at:          null;
    person:              Person;
}

export interface Person {
    id:               number;
    nombres:          string;
    apellido_paterno: string;
    apellido_materno: string;
}

export interface ProgramaEstudio {
    id:     number;
    nombre: string;
}

export interface Unit {
    id:                     number;
    course_id:              number;
    nombre:                 string;
    id_carga_curso_docente: string;
    id_carga_curso:         string;
    orden_unidad:           number;
    fecha_inicio:           null;
    fecha_fin:              null;
    topics:                 Topic[];
}

export interface Topic {
    id:                     number;
    unit_id:                number;
    contenido:              string;
    id_carga_curso_docente: string;
    id_carga_curso:         string;
    tema:                   Tema;
    fecha_tema:             Date;
    orden_tema:             number;
    elements:               any[];
}

export enum Tema {
    ListaDeCotejo = "Lista de cotejo - ",
    Rúbrica = "Rúbrica - ",
}
